<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="CylinderVtem" Id="{9c7ae81a-14b8-48a4-ac6a-92ee45d27ad6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CylinderVtem IMPLEMENTS ICylinder
VAR
	vtem				: VtemByFesto;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <Method Name="bwd" Id="{485b6fd1-a845-4d7d-8395-dd9a39a8045d}">
      <Declaration><![CDATA[METHOD bwd
]]></Declaration>
      <Implementation>
        <ST><![CDATA[vtem.moveBwd();]]></ST>
      </Implementation>
    </Method>
    <Method Name="fwd" Id="{464facca-7b17-4e91-b35c-993bb7d4f533}">
      <Declaration><![CDATA[METHOD fwd
]]></Declaration>
      <Implementation>
        <ST><![CDATA[vtem.moveFwd();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>