<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ec91c5d5-3c79-425d-bf90-5ff81ab84874}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* 
	GOF 		Define a family of algorithms, encapsulate each one, and make them interchangeable.
				Strategy lets the algorithm vary independently from clients using it.   
*)
P_Strategy();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>