<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{e2f91603-8361-47e1-9a31-a5fe20915a3c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* 
	GOF 		Define an object that encapsulates how a set of objects interact.
				Mediator promotes loose coupling by keeping objects from referring to each other
				explicitly, and it lets you vary their interaction independently   
*)
P_Mediator();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>