<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_StaticHandler_n" Id="{b27f75cc-7db2-0c1d-126c-3d51b98cb138}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StaticHandler_n EXTENDS FB_BaseHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="handle" Id="{8651466d-3bb6-025a-09d9-ba8112cfecf5}">
      <Declaration><![CDATA[METHOD handle : BOOL
VAR_INPUT
	request	:	STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_MSGBOX, request , '');
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>