<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ebd9d321-c781-405a-b1c2-e8d7fbcd71e2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* 
	GOF 		Allow an object to alter its behavior when its internal state changes.
				The object will appear to change its class.  
*)
P_State();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>