<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{1d0b0150-2786-4154-b48f-cfe959e84f55}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* 
	GOF 		Provide a surrogate or placeholder for another object to control access to it.
*)
P_Proxy();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>