<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5b114b34-9165-472c-a48a-33fbd2273da4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* 
	GOF 		Convert the interface of a class into another interface clients expect. Adapter
				lets classes work together that couldn't otherwise because of incompatible
				interfaces.
*)
P_Adapter();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>