<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8c51e295-a52e-48f0-8813-11e723eb2083}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* 
	GOF 		Represent an operation to be performed on the elements of an object structure.
				Visitor lets you define a new operation without changing the classes of the 
				elements on which it operates.
*)
P_Visitor();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>